stages:
  - build

build:1.20:
  stage: build
  image: golang:1.20
  script:
    - go version
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build xxwcli.go
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - xxwcli
  only:
    - main

#build:latest:macos:
#  stage: build
#  image: golang:latest
#  script:
#    - go version
#    - go env -w GOPROXY=https://goproxy.cn,direct
#    - go mod download
#    - go build xxwcli.go
#    - ls
#  artifacts:
#    name: "${CI_JOB_NAME}"
#    paths:
#      - xxwcli.out
#  tags:
#    - shared-macos-amd64
#  rules:
#    - if: $CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST != 'jihulab.com'

build:1.19.5-windowsservercore:
  stage: build
  image: golang:1.19.5-windowsservercore
  script:
    - go version
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build xxwcli.go
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - xxwcli.exe
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST != 'jihulab.com'
