# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Push Branches

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      CACHE_PATH: ~/go/pkg/mod/cache
      # 系统名称
      OS: ""
      # 时间
      YEAR_MONTH_DAY: ""
      YEAR_MONTH_DAY_HOUR: ""
      YEAR_MONTH_DAY_HOUR_MINUTE: ""
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        id: set-up-go
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          go version
          go mod download
          go build -ldflags "-X main.buildTime=$(date +%Y-%m-%d_%H:%M:%S%z) -X main.commitSha=$(git rev-parse HEAD) -X main.commitShortSha=$(git rev-parse --short HEAD) -X main.commitTimestamp=$(git log -1 --format="%cd" --date="format:%Y-%m-%d_%H:%M:%S%z")" xxwcli.go ||           go build -ldflags "-X main.buildTime=$(Get-Date -Format yyyy-MM-dd_HH:mm:ss%z) -X main.commitSha=$(git rev-parse HEAD) -X main.commitShortSha=$(git rev-parse --short HEAD) -X main.commitTimestamp=$(git log -1 --format="%cd" --date="format:%Y-%m-%d_%H:%M:%S%z")" xxwcli.go
          ./xxwcli -v || ./xxwcli.exe -v
          ./xxwcli v || ./xxwcli.exe v
          ls

      - name: Replace String Action
        uses: frabert/replace-string-action@v2
        id: replace
        with:
          pattern: '-latest$'
          string: ${{ matrix.os }}
          replace-with: ''

      - name: Set OS variable
        id: os
        run: |
          # 设置环境变量：支持 ubuntu、macos
          echo "OS=${{ steps.replace.outputs.replaced }}" >> $GITHUB_ENV
          # 设置环境变量：支持 windows
          echo "OS=${{ steps.replace.outputs.replaced }}" >> $env:GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xxwcli-${{ env.OS }}
          path: |
            xxwcli
            xxwcli.exe

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # if: startsWith(github.ref, 'refs/heads/main')
    steps:

      - name: Get current date
        id: date
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          echo "YEAR_MONTH_DAY=$(date +'%Y-%m-%dZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR=$(date +'%Y-%m-%dT%HZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR_MINUTE=$(date +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_ENV

      - name: Download Artifacts ubuntu
        uses: actions/download-artifact@v3
        with:
          name: xxwcli-ubuntu
          path: ubuntu

      - name: Download Artifacts windows
        uses: actions/download-artifact@v3
        with:
          name: xxwcli-windows
          path: windows

      - name: Download Artifacts macos
        uses: actions/download-artifact@v3
        with:
          name: xxwcli-macos
          path: macos

      - name: Copy & Rename
        run: |
          cp ./macos/xxwcli xxwcli-macos
          cp ./ubuntu/xxwcli xxwcli-ubuntu
          cp ./windows/xxwcli.exe xxwcli.exe

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xxwcli-macos
            xxwcli-ubuntu
            xxwcli.exe
          body:
            自动推送时的发布
          # draft: 草稿状态，为 true 时，不创建标签，默认为 false
          # draft: true
          # prerelease：是否发布预发布版，默认为 false
          prerelease: true
          name: ${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          tag: v${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          token: ${{ secrets.GITHUB_TOKEN }}
