# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Push Branches

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      CACHE_PATH: ~/go/pkg/mod/cache
      # 系统名称
      OS: ""
      # 时间
      YEAR_MONTH_DAY: ""
      YEAR_MONTH_DAY_HOUR: ""
      YEAR_MONTH_DAY_HOUR_MINUTE: ""
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        id: set-up-go
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          go version
          go mod download
          go build xxwcli.go
          ls

      - name: Set OS variable
        id: os
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          os=${{ matrix.os }}
          os=${{ os.replace('-latest', '') }}
          echo "OS=$os" >> $GITHUB_ENV

      - name: Get current date
        id: date
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          echo "YEAR_MONTH_DAY=$(date +'%Y-%m-%dZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR=$(date +'%Y-%m-%dT%HZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR_MINUTE=$(date +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xxwcli-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}-${{ env.OS }}
          path: |
            xxwcli
            xxwcli.exe

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xxwcli
            xxwcli.exe
          body:
            自动推送时的发布
          # draft: 草稿状态，为 true 时，不创建标签，默认为 false
          # draft: true
          # prerelease：是否发布预发布版，默认为 false
          prerelease: true
          name: ${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}-${{ env.OS }}
          tag: v${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}-${{ env.OS }}
          token: ${{ secrets.GITHUB_TOKEN }}
